### PR TITLE
Upgrade to toad-scheduler 2.0.0

### PR DESCRIPTION
**Pull request by kibertoad**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Eomm** [comment]
Please @kibertoad, could you wait for at least one review from one @fastify/plugins member?

I saw you have already released the v4, could you add a GH release as well?

I did manually the last one: https://github.com/fastify/fastify-schedule/releases/tag/v3.0.2
But I may don't see these kinds of changes in future

**Comment by kibertoad** [comment]
@Eomm Sorry for that. There wasn't much to review, it was pretty much straightforward bump. But I'll make sure to wait next time!

**Comment by Fdawgs** [comment]
@kibertoad, tag and release appear to be missing the leading `v`, which was present in other releases?

**Comment by kibertoad** [comment]
@Fdawgs my bad. will rename release and will be more careful in the future, sorry

**Pull request merged**
